'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MyWebService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Customer", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Customer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private address1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private address2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private stateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private zipField As String
        
        Private statusField As Integer
        
        Private customer_idField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property address1() As String
            Get
                Return Me.address1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.address1Field, value) <> true) Then
                    Me.address1Field = value
                    Me.RaisePropertyChanged("address1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property address2() As String
            Get
                Return Me.address2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.address2Field, value) <> true) Then
                    Me.address2Field = value
                    Me.RaisePropertyChanged("address2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property city() As String
            Get
                Return Me.cityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cityField, value) <> true) Then
                    Me.cityField = value
                    Me.RaisePropertyChanged("city")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property state() As String
            Get
                Return Me.stateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.stateField, value) <> true) Then
                    Me.stateField = value
                    Me.RaisePropertyChanged("state")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property zip() As String
            Get
                Return Me.zipField
            End Get
            Set
                If (Object.ReferenceEquals(Me.zipField, value) <> true) Then
                    Me.zipField = value
                    Me.RaisePropertyChanged("zip")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                If (Me.statusField.Equals(value) <> true) Then
                    Me.statusField = value
                    Me.RaisePropertyChanged("status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property customer_id() As Integer
            Get
                Return Me.customer_idField
            End Get
            Set
                If (Me.customer_idField.Equals(value) <> true) Then
                    Me.customer_idField = value
                    Me.RaisePropertyChanged("customer_id")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="MyWebService.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        'CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As MyWebService.HelloWorldRequest) As MyWebService.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As MyWebService.HelloWorldRequest) As System.Threading.Tasks.Task(Of MyWebService.HelloWorldResponse)
        
        'CODEGEN: Generating message contract since element name CustomerDeleteResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerDelete", ReplyAction:="*")>  _
        Function CustomerDelete(ByVal request As MyWebService.CustomerDeleteRequest) As MyWebService.CustomerDeleteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerDelete", ReplyAction:="*")>  _
        Function CustomerDeleteAsync(ByVal request As MyWebService.CustomerDeleteRequest) As System.Threading.Tasks.Task(Of MyWebService.CustomerDeleteResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerInsert", ReplyAction:="*")>  _
        Function CustomerInsert(ByVal request As MyWebService.CustomerInsertRequest) As MyWebService.CustomerInsertResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerInsert", ReplyAction:="*")>  _
        Function CustomerInsertAsync(ByVal request As MyWebService.CustomerInsertRequest) As System.Threading.Tasks.Task(Of MyWebService.CustomerInsertResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerSelect", ReplyAction:="*")>  _
        Function CustomerSelect(ByVal request As MyWebService.CustomerSelectRequest) As MyWebService.CustomerSelectResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerSelect", ReplyAction:="*")>  _
        Function CustomerSelectAsync(ByVal request As MyWebService.CustomerSelectRequest) As System.Threading.Tasks.Task(Of MyWebService.CustomerSelectResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerWrite", ReplyAction:="*")>  _
        Function CustomerWrite(ByVal request As MyWebService.CustomerWriteRequest) As MyWebService.CustomerWriteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerWrite", ReplyAction:="*")>  _
        Function CustomerWriteAsync(ByVal request As MyWebService.CustomerWriteRequest) As System.Threading.Tasks.Task(Of MyWebService.CustomerWriteResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CustomerDeleteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CustomerDelete", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.CustomerDeleteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.CustomerDeleteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CustomerDeleteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public customer_id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customer_id As Integer)
            MyBase.New
            Me.customer_id = customer_id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CustomerDeleteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CustomerDeleteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.CustomerDeleteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.CustomerDeleteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CustomerDeleteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CustomerDeleteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CustomerDeleteResult As String)
            MyBase.New
            Me.CustomerDeleteResult = CustomerDeleteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CustomerInsertRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CustomerInsert", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.CustomerInsertRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.CustomerInsertRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CustomerInsertRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public newCustomer As MyWebService.Customer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal newCustomer As MyWebService.Customer)
            MyBase.New
            Me.newCustomer = newCustomer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CustomerInsertResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CustomerInsertResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.CustomerInsertResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.CustomerInsertResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CustomerInsertResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CustomerInsertResult As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public newCustomer As MyWebService.Customer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CustomerInsertResult As String, ByVal newCustomer As MyWebService.Customer)
            MyBase.New
            Me.CustomerInsertResult = CustomerInsertResult
            Me.newCustomer = newCustomer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CustomerSelectRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CustomerSelect", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.CustomerSelectRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.CustomerSelectRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CustomerSelectRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public searchCustomer As MyWebService.Customer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal searchCustomer As MyWebService.Customer)
            MyBase.New
            Me.searchCustomer = searchCustomer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CustomerSelectResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CustomerSelectResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.CustomerSelectResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.CustomerSelectResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CustomerSelectResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CustomerSelectResult() As MyWebService.Customer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public searchCustomer As MyWebService.Customer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CustomerSelectResult() As MyWebService.Customer, ByVal searchCustomer As MyWebService.Customer)
            MyBase.New
            Me.CustomerSelectResult = CustomerSelectResult
            Me.searchCustomer = searchCustomer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CustomerWriteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CustomerWrite", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.CustomerWriteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.CustomerWriteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CustomerWriteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public updateCustomer As MyWebService.Customer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updateCustomer As MyWebService.Customer)
            MyBase.New
            Me.updateCustomer = updateCustomer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CustomerWriteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CustomerWriteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MyWebService.CustomerWriteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MyWebService.CustomerWriteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CustomerWriteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CustomerWriteResult As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public updateCustomer As MyWebService.Customer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CustomerWriteResult As String, ByVal updateCustomer As MyWebService.Customer)
            MyBase.New
            Me.CustomerWriteResult = CustomerWriteResult
            Me.updateCustomer = updateCustomer
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits MyWebService.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of MyWebService.WebService1Soap)
        Implements MyWebService.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_HelloWorld(ByVal request As MyWebService.HelloWorldRequest) As MyWebService.HelloWorldResponse Implements MyWebService.WebService1Soap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As MyWebService.HelloWorldRequest = New MyWebService.HelloWorldRequest()
            inValue.Body = New MyWebService.HelloWorldRequestBody()
            Dim retVal As MyWebService.HelloWorldResponse = CType(Me,MyWebService.WebService1Soap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_HelloWorldAsync(ByVal request As MyWebService.HelloWorldRequest) As System.Threading.Tasks.Task(Of MyWebService.HelloWorldResponse) Implements MyWebService.WebService1Soap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of MyWebService.HelloWorldResponse)
            Dim inValue As MyWebService.HelloWorldRequest = New MyWebService.HelloWorldRequest()
            inValue.Body = New MyWebService.HelloWorldRequestBody()
            Return CType(Me,MyWebService.WebService1Soap).HelloWorldAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_CustomerDelete(ByVal request As MyWebService.CustomerDeleteRequest) As MyWebService.CustomerDeleteResponse Implements MyWebService.WebService1Soap.CustomerDelete
            Return MyBase.Channel.CustomerDelete(request)
        End Function
        
        Public Function CustomerDelete(ByVal customer_id As Integer) As String
            Dim inValue As MyWebService.CustomerDeleteRequest = New MyWebService.CustomerDeleteRequest()
            inValue.Body = New MyWebService.CustomerDeleteRequestBody()
            inValue.Body.customer_id = customer_id
            Dim retVal As MyWebService.CustomerDeleteResponse = CType(Me,MyWebService.WebService1Soap).CustomerDelete(inValue)
            Return retVal.Body.CustomerDeleteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_CustomerDeleteAsync(ByVal request As MyWebService.CustomerDeleteRequest) As System.Threading.Tasks.Task(Of MyWebService.CustomerDeleteResponse) Implements MyWebService.WebService1Soap.CustomerDeleteAsync
            Return MyBase.Channel.CustomerDeleteAsync(request)
        End Function
        
        Public Function CustomerDeleteAsync(ByVal customer_id As Integer) As System.Threading.Tasks.Task(Of MyWebService.CustomerDeleteResponse)
            Dim inValue As MyWebService.CustomerDeleteRequest = New MyWebService.CustomerDeleteRequest()
            inValue.Body = New MyWebService.CustomerDeleteRequestBody()
            inValue.Body.customer_id = customer_id
            Return CType(Me,MyWebService.WebService1Soap).CustomerDeleteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_CustomerInsert(ByVal request As MyWebService.CustomerInsertRequest) As MyWebService.CustomerInsertResponse Implements MyWebService.WebService1Soap.CustomerInsert
            Return MyBase.Channel.CustomerInsert(request)
        End Function
        
        Public Function CustomerInsert(ByRef newCustomer As MyWebService.Customer) As String
            Dim inValue As MyWebService.CustomerInsertRequest = New MyWebService.CustomerInsertRequest()
            inValue.Body = New MyWebService.CustomerInsertRequestBody()
            inValue.Body.newCustomer = newCustomer
            Dim retVal As MyWebService.CustomerInsertResponse = CType(Me,MyWebService.WebService1Soap).CustomerInsert(inValue)
            newCustomer = retVal.Body.newCustomer
            Return retVal.Body.CustomerInsertResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_CustomerInsertAsync(ByVal request As MyWebService.CustomerInsertRequest) As System.Threading.Tasks.Task(Of MyWebService.CustomerInsertResponse) Implements MyWebService.WebService1Soap.CustomerInsertAsync
            Return MyBase.Channel.CustomerInsertAsync(request)
        End Function
        
        Public Function CustomerInsertAsync(ByVal newCustomer As MyWebService.Customer) As System.Threading.Tasks.Task(Of MyWebService.CustomerInsertResponse)
            Dim inValue As MyWebService.CustomerInsertRequest = New MyWebService.CustomerInsertRequest()
            inValue.Body = New MyWebService.CustomerInsertRequestBody()
            inValue.Body.newCustomer = newCustomer
            Return CType(Me,MyWebService.WebService1Soap).CustomerInsertAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_CustomerSelect(ByVal request As MyWebService.CustomerSelectRequest) As MyWebService.CustomerSelectResponse Implements MyWebService.WebService1Soap.CustomerSelect
            Return MyBase.Channel.CustomerSelect(request)
        End Function
        
        Public Function CustomerSelect(ByRef searchCustomer As MyWebService.Customer) As MyWebService.Customer()
            Dim inValue As MyWebService.CustomerSelectRequest = New MyWebService.CustomerSelectRequest()
            inValue.Body = New MyWebService.CustomerSelectRequestBody()
            inValue.Body.searchCustomer = searchCustomer
            Dim retVal As MyWebService.CustomerSelectResponse = CType(Me,MyWebService.WebService1Soap).CustomerSelect(inValue)
            searchCustomer = retVal.Body.searchCustomer
            Return retVal.Body.CustomerSelectResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_CustomerSelectAsync(ByVal request As MyWebService.CustomerSelectRequest) As System.Threading.Tasks.Task(Of MyWebService.CustomerSelectResponse) Implements MyWebService.WebService1Soap.CustomerSelectAsync
            Return MyBase.Channel.CustomerSelectAsync(request)
        End Function
        
        Public Function CustomerSelectAsync(ByVal searchCustomer As MyWebService.Customer) As System.Threading.Tasks.Task(Of MyWebService.CustomerSelectResponse)
            Dim inValue As MyWebService.CustomerSelectRequest = New MyWebService.CustomerSelectRequest()
            inValue.Body = New MyWebService.CustomerSelectRequestBody()
            inValue.Body.searchCustomer = searchCustomer
            Return CType(Me,MyWebService.WebService1Soap).CustomerSelectAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_CustomerWrite(ByVal request As MyWebService.CustomerWriteRequest) As MyWebService.CustomerWriteResponse Implements MyWebService.WebService1Soap.CustomerWrite
            Return MyBase.Channel.CustomerWrite(request)
        End Function
        
        Public Function CustomerWrite(ByRef updateCustomer As MyWebService.Customer) As String
            Dim inValue As MyWebService.CustomerWriteRequest = New MyWebService.CustomerWriteRequest()
            inValue.Body = New MyWebService.CustomerWriteRequestBody()
            inValue.Body.updateCustomer = updateCustomer
            Dim retVal As MyWebService.CustomerWriteResponse = CType(Me,MyWebService.WebService1Soap).CustomerWrite(inValue)
            updateCustomer = retVal.Body.updateCustomer
            Return retVal.Body.CustomerWriteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MyWebService_WebService1Soap_CustomerWriteAsync(ByVal request As MyWebService.CustomerWriteRequest) As System.Threading.Tasks.Task(Of MyWebService.CustomerWriteResponse) Implements MyWebService.WebService1Soap.CustomerWriteAsync
            Return MyBase.Channel.CustomerWriteAsync(request)
        End Function
        
        Public Function CustomerWriteAsync(ByVal updateCustomer As MyWebService.Customer) As System.Threading.Tasks.Task(Of MyWebService.CustomerWriteResponse)
            Dim inValue As MyWebService.CustomerWriteRequest = New MyWebService.CustomerWriteRequest()
            inValue.Body = New MyWebService.CustomerWriteRequestBody()
            inValue.Body.updateCustomer = updateCustomer
            Return CType(Me,MyWebService.WebService1Soap).CustomerWriteAsync(inValue)
        End Function
    End Class
End Namespace
